apiVersion: apps/v1
kind: Deployment
metadata:
  name: dask-worker-deployment
spec:
  selector:
    matchLabels:
      component: worker
  replicas: {{ .Values.worker.replicas }}
  strategy:
    type: {{ .Values.worker.strategy.type }}
  template:
    metadata:
      labels:
        component: worker
    spec:
      {{- if .Values.worker.mounts.volumes }}
      volumes:
        {{- toYaml .Values.worker.mounts.volumes | nindent 8}}
      {{- end }}
      containers:
        - name: dask-worker
          image: "{{ .Values.worker.image.name }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          args:
            - dask-worker
            - {{ .Values.scheduler.serviceName }}:8786
            - --no-dashboard
            - --dashboard-address
            - {{ .Values.worker.portDashboard | quote }}
          ports:
            - containerPort: {{ .Values.worker.portDashboard }}
              name: dashboard
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          env:
            {{- toYaml .Values.worker.env | nindent 12 }}
          {{- if .Values.worker.mounts.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.worker.mounts.volumeMounts | nindent 12 }}
          {{- end }}
    {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
