scheduler:
  image:
    name: dalmatialab/dask
    tag: 2021.9.1
    pullPolicy: Always 
  replicas: 1
  nodeSelector: {}
  env:
  #  - name: EXTRA_APT_PACKAGES
  #    value: vim nano
  #  - name: EXTRA_PIP_PACKAGES
  #    value: shapely datetime
  serviceName: 
  nodePort: 
  webui:
    nodePort:

worker:
  image:
    name: dalmatialab/dask
    tag: 2021.9.1
    pullPolicy: Always
  replicas: 2
  strategy:
    type: RollingUpdate
  env:
  #  - name: EXTRA_APT_PACKAGES
  #    value: vim nano
  #  - name: EXTRA_PIP_PACKAGES
  #    value: shapely datetime
  resources: {}
#    requests:
#      cpu: 1
#      memory: 10G
  mounts: {}
#    volumes:
#      - name: 
#        hostPath:
#          path: 
#    volumeMounts:
#      - name: 
#        mountPath:
  nodeSelector: { daskworker: "true"}
  portDashboard: 8790